// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TransferenciaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240918182613_SeedCuentas")]
    partial class SeedCuentas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cuenta", b =>
                {
                    b.Property<int>("CuentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CuentaId"));

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric");

                    b.HasKey("CuentaId");

                    b.ToTable("Cuentas");

                    b.HasData(
                        new
                        {
                            CuentaId = 1,
                            NumeroCuenta = "1234567890",
                            Saldo = 1000.00m
                        },
                        new
                        {
                            CuentaId = 2,
                            NumeroCuenta = "0987654321",
                            Saldo = 500.00m
                        });
                });

            modelBuilder.Entity("Transferencia", b =>
                {
                    b.Property<int>("TransferenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransferenciaId"));

                    b.Property<int>("CuentaDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("CuentaOrigenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaTransferencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.HasKey("TransferenciaId");

                    b.HasIndex("CuentaDestinoId");

                    b.HasIndex("CuentaOrigenId");

                    b.ToTable("Transferencias");
                });

            modelBuilder.Entity("Transferencia", b =>
                {
                    b.HasOne("Cuenta", "CuentaDestino")
                        .WithMany("TransferenciasRecibidas")
                        .HasForeignKey("CuentaDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cuenta", "CuentaOrigen")
                        .WithMany("TransferenciasEnviadas")
                        .HasForeignKey("CuentaOrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaDestino");

                    b.Navigation("CuentaOrigen");
                });

            modelBuilder.Entity("Cuenta", b =>
                {
                    b.Navigation("TransferenciasEnviadas");

                    b.Navigation("TransferenciasRecibidas");
                });
#pragma warning restore 612, 618
        }
    }
}
